### ISSUE TITLE
address-troubles/question

### ISSUE THREAD

**Issue by neuki** [input-output-hk/cardano-addresses#111]
Hi!
Today i have made an test with cardano-address and generated a public address from my 24 word seed:
```
cat ./seed.txt | cardano-address key from-recovery-phrase Shelley > ./priv.txt
cat ./priv.txt | cardano-address key child 1852H/1815H/0H/0/0 > ./xpriv.txt 
cat ./xpriv.txt | cardano-address key public --with-chain-code | \
      cardano-address address payment --network-tag mainnet > ./firstPublicAddress
```
I got a valid public address! With the same 24 word seed i restored a new yoroi-wallet in Chrome, exported as readonly-wallet and installed it on my mobilephone. After that, i spend one ADA to the new generated 'firstPublicAddress' from above. The transaction was confirmed by the network, but never comes in?! 
If i generate an address with the yoroi-app, i can normal receive coins.

What i am doing wrong? Should this not work?

I noticed, that the public addresses generated with cli-cardano-address are shorter than from yoroi - what is the reason for that?
Thxs!

**Comment by neuki** [comment]
To reproduce the problem:
seed phrase:
```
stamp health brass raise plug permit airport pilot planet absent inform renew tribe face write slight oil token spin tell roof forget mystery law
```
firstPublicAddress:
```
addr1vxm42hlk4w2g99uceald4uldmc0jvwld8wjd0umv4a3a3gqcya4cr
```

**Comment by KtorZ** [comment]
This looks like an issue with Yoroi, I'd suggest to open a ticket on [Emurgo's repository](https://github.com/Emurgo/yoroi-frontend/). 

What you're describing (i.e. the root key generation, derivation and address creation) seems okay and I'd indeed expect Daedalus to discover such address. Yet, your address does not include any stake part (see the section "How to generate a delegated payment address from a stake key (payment-delegated.addr)" on the README) which explains why it is shorter and, may explain why Yoroi discover them. 
Daedalus will recognize non-delegated addresses because it recognizes the payment part of the address; it could be however that Yoroi only consider fully delegated addresses and treat base addresses differently (or simply ignore them).
