### ISSUE TITLE
Transform Shelley Address type

### ISSUE THREAD

**Issue by RootGoFly** [input-output-hk/cardano-addresses#184]
![image](https://user-images.githubusercontent.com/98209411/162876615-4f9ffc5c-2860-4a6f-9ac4-7f3f64a4a2f3.png)
There are payment part and delegation part in Shelley addresses. Is it possible that transform _type0 address_  (with both parts) to _type6 address_ (only with payment part)? If it is possible, how should I do?

**Comment by paweljakubas** [comment]
Hi @RootGoFly ,

Let's go through an example to see the case : 
1. Let's assume we have `phrase.prv`: 
```
exercise club noble adult miracle awkward problem olympic puppy private goddess piano fatal fashion vacuum
```
2. we create `root.xsk`
```
$ cardano-address key from-recovery-phrase Shelley < phrase.prv > roo.xsk
root_xsk1hqzfzrgskgnpwskxxrv5khs7ess82ecy8za9l5ef7e0afd2849p3zryje8chk39nxtva0sww5me3pzkej4rvd5cae3q3v8eu7556n6pdrp4fdu8nsglynpmcppxxvfdyzdz5gfq3fefjepxhvqspmuyvmvqg8983
```
3. now we can create payment credential:
```
$ cardano-address key child 1852H/1815H/0H/0/0 < root.xsk | cardano-address key public --with-chain-code
addr_xvk1grvg8qzmkmw2n0dm4pd0h3j4dv6yglyammyp733eyj629dc3z28v6wk22nfmru6xz0vl2s3y5xndyd57fu70hrt84c6zkvlwx6fdl7ct9j7yc > addr.xvk
$ cardano-address key child 1852H/1815H/0H/0/0 < root.xsk | cardano-address key public --with-chain-code | cardano-address key hash > addr.vkh
addr_vkh12j28hnmtwcp3n08vy58vyf0arnnrhtavu3lrfdztw0j0jng3d6v
```
4. We create stake credential : 
```
$ cardano-address key child 1852H/1815H/0H/2/0 < root.xsk | cardano-address key public --with-chain-code | cardano-address key hash > stake.vkh
stake_vkh17mf09mecwve7zkh2jve7nkggu4azk5f7cmtk9zz0wzhz5efq2w6
```
5. We create enterprise address (type 6): 
```
$ cardano-address address payment --network-tag testnet < addr.xvk
addr_test1vp2fg770ddmqxxduasjsas39l5wwvwa04nj8ud95fde7f7guscp6v
$ cardano-address address payment --network-tag testnet < addr.vkh
addr_test1vp2fg770ddmqxxduasjsas39l5wwvwa04nj8ud95fde7f7guscp6v
```
6. we create base address (type 0) from point 5 and stake.vkh (but can also from stake.xvk or stake.vk)
```
$ cardano-address address delegation $(cat stake.xvk) < payment.addr
addr_test1qp2fg770ddmqxxduasjsas39l5wwvwa04nj8ud95fde7f70k6tew7wrnx0s4465nx05ajz890g44z0kx6a3gsnms4c4qq8ve0n
```
7. In order to go from base address to enterprise address we can use inspect
```
$ echo addr_test1qp2fg770ddmqxxduasjsas39l5wwvwa04nj8ud95fde7f70k6tew7wrnx0s4465nx05ajz890g44z0kx6a3gsnms4c4qq8ve0n | cardano-address address inspect
{
    "stake_reference": "by value",
    "stake_key_hash_bech32": "stake_vkh17mf09mecwve7zkh2jve7nkggu4azk5f7cmtk9zz0wzhz5efq2w6",
    "stake_key_hash": "f6d2f2ef387333e15aea9333e9d908e57a2b513ec6d762884f70ae2a",
    "spending_key_hash_bech32": "addr_vkh12j28hnmtwcp3n08vy58vyf0arnnrhtavu3lrfdztw0j0jng3d6v",
    "address_style": "Shelley",
    "spending_key_hash": "54947bcf6b760319bcec250ec225fd1ce63baface47e34b44b73e4f9",
    "network_tag": 0,
    "address_type": 0
}
```
As you see we have the same `stake_key_hash_bech32` as in point 4. `spending_key_hash` is in hex, `spending_key_hash_bech32` as in point 3. 
This is consistent with point 3. So now you can use this payment credential to get enterprise address (type 0):
```
$ cardano-address address payment --network-tag testnet < addr.vkh
addr_test1vp2fg770ddmqxxduasjsas39l5wwvwa04nj8ud95fde7f7guscp6v
```

You can double check hex and bech32 correspondence using  https://github.com/input-output-hk/bech32 to transform hex representation to bech32 with prefix `addr_vkh` : 
```
bech32 addr_vkh <<< 54947bcf6b760319bcec250ec225fd1ce63baface47e34b44b73e4f9
addr_vkh12j28hnmtwcp3n08vy58vyf0arnnrhtavu3lrfdztw0j0jng3d6v
```

**Comment by paweljakubas** [comment]
Also please notice that this kind of functionality, ie. constructing credentials from key hashes besides extended public keys come with this release https://github.com/input-output-hk/cardano-addresses/releases/tag/3.12.0
Very soon, there will be support for all possible ways: from key hash, from script, from script hash, from extended and non-extended public keys.
